# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:

    php:
        container_name: nsd_oim_php
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: 
            context: ./images/php
            dockerfile: Dockerfile

        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www

    nginx:
      # используем последний стабильный образ nginx
        image: nginx:latest
        container_name: nsd_oim
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        #depends_on:
           # - test

    mysql:
        image: "mysql:8"
        container_name: nsd_oim_mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: secret